import os
import subprocess
from pathlib import Path
import argparse
import time

#################################
# OBLIVIATOR OPERATOR 1 WRAPPER #
#################################

def obliviator_operator1 (
    filepath: str,
    operator1_variant: str = "default" # "default" for ~/operator_1, "opaque_shared_memory" for the other
):
    """
    Runs Obliviator's "Operator 1" which performs a projection.

    Args:
        filepath (str): Path to the input data file (e.g., test.txt).
        operator1_variant (str): Specifies which Operator 1 implementation to use.
                                "default" for ~/obliviator/operator_1/
                                "opaque_shared_memory" for ~/obliviator/opaque_shared_memory/operator_1/
    """
    print(f"Running oblivious Operator 1 (variant: {operator1_variant}) on {filepath}")

    # Create temp directory
    temp_dir = Path("tmp_operator1") # Use a separate temp directory
    temp_dir.mkdir(exist_ok=True)
    print("Created temp directory " + str(temp_dir))

    #########################################
    # 1. Format input for Obliviator Operator 1 #
    #########################################

    # This calls format_operator1.py to preprocess the raw input file.
    # format_operator1.py will extract relevant columns and prepare
    # the data in a format suitable for relabeling (e.g., ID string_part).
    print("Formatting input for Obliviator Operator 1...")
    format_path = temp_dir / "op1_format.txt"
    subprocess.run([
        "python", "obliviator_formatting/format_operator1.py",
        "--filepath", filepath,
        "--output_path", str(format_path)
    ], check=True, cwd=Path(__file__).parent)
    print("Formatted input written to " + str(format_path) + ".")

    ###################################################
    # 2. Relabel IDs to reduce into Obliviators range #
    ###################################################

    # Relabel the IDs generated by format_operator1.py.
    # This generates a new file with contiguous integer IDs and a mapping file.
    print("Relabeling IDs for Operator 1 input...")
    relabel_path = temp_dir / "op1_relabel.txt"
    mapping_path = temp_dir / "op1_map.txt"
    subprocess.run([
        "python", "obliviator_formatting/relabel_ids.py",
        "--input_path", str(format_path),
        "--output_path", str(relabel_path),
        "--mapping_path", str(mapping_path)
    ], check=True, cwd=Path(__file__).parent)
    print("Relabeled input written to " + str(relabel_path) + ", relabel map written to " + str(mapping_path) + ".")

    ##############################
    # 3. Run Obliviator Operator 1 #
    ##############################

    print(f"Running Obliviator Operator 1 ({operator1_variant} variant)...")

    # Determine the correct code directory for the obliviator binary
    if operator1_variant == "default":
        code_dir = Path(os.path.expanduser("~/obliviator/operator_1"))
    elif operator1_variant == "opaque_shared_memory":
        code_dir = Path(os.path.expanduser("~/obliviator/opaque_shared_memory/operator_1"))
    else:
        raise ValueError(f"Unknown operator1_variant: {operator1_variant}. Choose 'default' or 'opaque_shared_memory'.")

    print(f"Building Obliviator Operator 1 ({operator1_variant})...")
    subprocess.run(["make", "clean"], cwd=code_dir, check=True)
    subprocess.run(["make"], cwd=code_dir, check=True)

    # Get the absolute path to the relabeled input file.
    # This path will be passed to the obliviator executable.
    absolute_path_to_input = (Path(__file__).parent / relabel_path).resolve()

    print(f"Build completed. Executing Operator 1 with input: {absolute_path_to_input} (absolute path)")
    print(f"obliviator executable will run from CWD: {code_dir}")

    # Execute Operator 1. The output is written to a file within code_dir.
    # Removed check=True to prevent CalledProcessError if obliviator exits with non-zero on success.
    subprocess.run(
        ["./host/parallel", "./enclave/parallel_enc.signed", "1", str(absolute_path_to_input)],
        cwd=code_dir
        # check=True removed here
    )
    print("Exited Obliviator Operator 1 successfully.")

    # --- Find and Copy Obliviator's Raw Output ---
    # The output file name generated by obliviator is based on the input file's stem.
    # It writes to the SAME DIRECTORY as the input file (tmp_operator1), NOT the code_dir.
    obliviator_raw_output_filename = relabel_path.stem + "_output.txt"
    obliviator_raw_output_path_absolute = temp_dir / obliviator_raw_output_filename # CORRECTED: Look in temp_dir

    print(f"DEBUG: Expected raw Obliviator output filename: {obliviator_raw_output_filename}")
    print(f"DEBUG: Python will look for Obliviator output at: {obliviator_raw_output_path_absolute}")

    # Define the path where the raw obliviator output will be copied to within our temp directory
    obliv_op1_output_path = temp_dir / "obliv_op1_output.txt"

    try:
        # Check if the output file exists in the expected location
        if not obliviator_raw_output_path_absolute.exists():
            print(f"DEBUG: Contents of {temp_dir}: {[item.name for item in temp_dir.iterdir()]}") # Debug print
            raise FileNotFoundError(f"Obliviator output file not found: {obliviator_raw_output_path_absolute}")

        # Read content from the obliviator's raw output file
        with open(obliviator_raw_output_path_absolute, "r") as infile:
            content = infile.read()

        # Write content to our wrapper's temp output file
        with open(obliv_op1_output_path, "w") as outfile:
            outfile.write(content)
        print(f"Copied raw Obliviator output from {obliviator_raw_output_path_absolute} to {obliv_op1_output_path}.")

    except FileNotFoundError as e:
        print(f"Error: {e}")
        print("Please ensure the Obliviator Operator 1 executable correctly writes its output.")
        return # Exit the function if the file isn't found
    except Exception as e:
        print(f"An unexpected error occurred while processing Obliviator output: {e}")
        return

    ######################
    # 4. Reverse Relabel #
    ######################

    # Reverse relabel the IDs in the output.
    # The `reverse_relabel_ids.py` handles 2-column output (ID SPACE string_part).
    # It will remap the ID and pass the string_part through unchanged.
    print("Reverse-relabeling IDs for Operator 1 output and projecting string parts...")
    final_output_path = temp_dir / "op1_output.txt"

    subprocess.run([
        "python", "obliviator_formatting/reverse_relabel_ids.py",
        "--input_path", str(obliv_op1_output_path),
        "--output_path", str(final_output_path),
        "--mapping_path", str(mapping_path)
    ], check=True, cwd=Path(__file__).parent)
    print("Reverse-relabeled Operator 1 output written to " + str(final_output_path) + ".\n\n")

    print(f"✅ Output of Obliviator Operator 1 written to: {final_output_path}\n\n")
    return


def main():
    parser = argparse.ArgumentParser()
    # Default filepath for testing. Ensure this points to your Operator 1 test.txt
    parser.add_argument("--filepath", default="data/test_operator1.txt")
    parser.add_argument("--operator1_variant", choices=["default", "opaque_shared_memory"], default="default",
                        help="Specify the Operator 1 variant.")
    args = parser.parse_args()

    obliviator_operator1(args.filepath, args.operator1_variant)


if __name__ == "__main__":
    main()

